# Project 01 - Color Compression

## Thông tin sinh viên

- Họ và tên:
- MSSV:
- Lớp:

## Import các thư viện liên quan

In [107]:
import matplotlib.pyplot as plt
import PIL
import numpy as np
import math

## Helper functions

In [108]:
import PIL.Image


def read_img(img_path):
    '''
    Read image from img_path

    Parameters
    ----------
    img_path : str
        Path of image

    Returns
    -------
        Image (2D)
    '''

    # YOUR CODE HERE
    return PIL.Image.open(img_path)

def show_img(img_2d):
    '''
    Show image

    Parameters
    ----------
    img_2d : <your type>
        Image (2D)
    '''

    # YOUR CODE HERE
    plt.imshow(img_2d)

def save_img(img_2d, img_path):
    '''
    Save image to img_path

    Parameters
    ----------
    img_2d : <your type>
        Image (2D)
    img_path : str
        Path of image
    '''
    
    # YOUR CODE HERE
    img_2d.save(img_path, 'PNG')

def convert_img_to_1d(img_2d):
    '''
    Convert 2D image to 1D image

    Parameters
    ----------
    img_2d : <your type>
        Image (2D)

    Returns
    -------
        Image (1D)
    '''
    
    # YOUR CODE HERE
    A = np.asarray(img_2d)
    X = A.reshape(A.shape[0] * A.shape[1], A.shape[2])
    return X

def kmeans(img_1d, k_clusters, max_iter, init_centroids='random'):
    '''
    K-Means algorithm

    Parameters
    ----------
    img_1d : np.ndarray with shape=(height * width, num_channels)
        Original (1D) image
    k_clusters : int
        Number of clusters
    max_iter : int
        Max iterator
    init_centroids : str, default='random'
        The method used to initialize the centroids for K-means clustering
        'random' --> Centroids are initialized with random values between 0 and 255 for each channel
        'in_pixels' --> A random pixel from the original image is selected as a centroid for each cluster

    Returns
    -------
    centroids : np.ndarray with shape=(k_clusters, num_channels)
        Stores the color centroids for each cluster
    labels : np.ndarray with shape=(height * width, )
        Stores the cluster label for each pixel in the image
    '''
    
    # YOUR CODE HERE


def generate_2d_img(img_2d_shape, centroids, labels):
    '''
    Generate a 2D image based on K-means cluster centroids

    Parameters
    ----------
    img_2d_shape : tuple (height, width, 3)
        Shape of image
    centroids : np.ndarray with shape=(k_clusters, num_channels)
        Store color centroids
    labels : np.ndarray with shape=(height * width, )
        Store label for pixels (cluster's index on which the pixel belongs)

    Returns
    -------
        New image (2D)
    '''

    # YOUR CODE HERE


# Your additional functions here


## Your tests

In [109]:
# YOUR CODE HERE

## Main FUNCTION

In [110]:
# YOUR CODE HERE

In [111]:
# Call main function

# TESTING ZONE


In [ ]:
# https://www.youtube.com/watch?v=5w5iUbTlpMQ
# https://www.youtube.com/watch?v=8mUi6U_5ZCg

def kmeans(img_1d, k_clusters, max_iter, init_centroids='random'):
    '''
    K-Means algorithm

    Parameters
    ----------
    img_1d : np.ndarray with shape=(height * width, num_channels)
        Original (1D) image
    k_clusters : int
        Number of clusters
    max_iter : int
        Max iterator
    init_centroids : str, default='random'
        The method used to initialize the centroids for K-means clustering
        'random' --> Centroids are initialized with random values between 0 and 255 for each channel
        'in_pixels' --> A random pixel from the original image is selected as a centroid for each cluster

    Returns
    -------
    centroids : np.ndarray with shape=(k_clusters, num_channels)
        Stores the color centroids for each cluster
    labels : np.ndarray with shape=(height * width, )
        Stores the cluster label for each pixel in the image
    '''
    
    # YOUR CODE HERE


class KMeansClustering:
    def __init__(self, k = 3):
        self.k = k
        self.centroids = None

    def fit(self, X, max_iter = 100): # X: 1D Image
        self.centroids = np.random.uniform(np.min(X, axis=0), np.max(X, axis=0), size=(self.k, X.shape[1]))

        for 


In [136]:
# testImgPath =  'C:\\Users\\Admin\\Documents\\HCMUS\\Year 2\\Applied_Math\\Picture\\undefined - Imgur.png'
testImgPath =  'C:\\Users\\Admin\\Documents\\HCMUS\\Year 2\\Applied_Math\\Picture\\2456269.jpg'
testImg = read_img(testImgPath)
convert_img_to_1d(testImg)
oriArray = np.asarray(testImg)
newArray = oriArray.reshape(oriArray.shape[0]*oriArray.shape[1], oriArray.shape[2])

k = 6

centroids = np.random.uniform(np.min(newArray, axis=0), np.max(newArray, axis=0), size=(k, newArray.shape[1]))
# centroids_2 = np.random.uniform(np.min(newArray), np.max(newArray), size=(k, newArray.shape[1]))
print(newArray.shape)

print(centroids)

random_points = np.random.randint(0, 100, (100, 2))
random_points.shape

# show_img(testImg)
# A = np.asarray(testImg)
# newImg = PIL.Image.fromarray(A*3)

# newPath = 'C:\\Users\\Admin\\Documents\\HCMUS\\Year 2\\Applied_Math\\Picture\\whatisthis.png'
# save_img(newImg, newPath)

(4194304, 3)
[[ 75.38181812 133.57858352  66.44114554]
 [233.89996304  56.20790727 126.70282429]
 [ 76.84663823 224.65630316  43.88347084]
 [164.05058074  37.70605474  25.36633363]
 [182.99786533 188.60385279  46.6978235 ]
 [ 13.6462462   16.56373356 122.29563137]]


(100, 2)